plugins:
  billboard_enabled:
    default: true
    client: true
  billboard_display_min_trust_level:
    default: 0
    enum: 'TrustLevelSetting'
    client: true
  billboard_target_user:
    default: 'siwei'
    client: true